version: "3.8"

services:
  frontend:
    build:
      context: ./front
    ports:
      - "8081:80"
    volumes:
      - ./front:/var/www/html

  backend:
    build:
      context: ./back
    ports:
      - "8080:80"
    depends_on:
      - database
    volumes:
      - ./back:/var/www/html

  database:
    image: mariadb:10.4
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: formulario
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
